### ISSUE TITLE
minor issue I noticed

### ISSUE THREAD

**Issue by ANaPhOrAX** [NumyAddon/InviteOnWhisper#1]
When it says "Trying to invite" there's no space between 'invite' and the player name

**Comment by ANaPhOrAX** [comment]
btw another thing I just noticed is, if people whisper me 'inv' but if their message contains anything else like a "please" or a smiley like :D or :) or whatever, the message gets ignored. would it be possible to implement a setting to where you can choose to have any message that includes a certain word or phrase to function as a trigger? because okay sure I've been adding all the variations people have whispered me so far, but you can never account for everything o_X

**Comment by Numynum** [comment]
fixed in next update
I've also clarified the Smart Match option (though since you deleted your other comment, I guess you figured out what it does ^^), it was indeed quite confusing

**Comment by ANaPhOrAX** [comment]
haha yeah I did, and once I figured it out I felt like an idiot so decided to remove that part of my post xd but thank you for the extra clarification, never a bad thing!
